name: 🧪 Test Local

on:
  workflow_dispatch:
    inputs:
      emergency:
        description: 'Emergency mode - Skip CI for team members'
        required: false
        type: boolean
        default: false

jobs:
  check-team:
    name: Check Actor
    runs-on: ubuntu-latest
    outputs:
      is_team_member: ${{ steps.check_allowed.outputs.is_team_member }}
    steps:
      - uses: actions/checkout@v4
      - id: check_allowed
        uses: ./.github/actions/check-team-member
        with:
          team: 'example'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: 🧪 Test
    needs: check-team
    if: ${{ !(inputs.emergency && needs.check-team.outputs.is_team_member == 'true') || !inputs.emergency }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Info
        run: |
          echo "Current user: ${{ github.actor }}"
          echo "Emergency mode: ${{ inputs.emergency }}"
          echo "Is team member: ${{ needs.check-team.outputs.is_team_member }}"
          echo "Workflow will run: ${{ !(inputs.emergency && needs.check-team.outputs.is_team_member == 'true') || !inputs.emergency }}"

      - name: Simulate Test
        run: |
          echo "Running test simulation..."
          sleep 5
          echo "Test completed successfully!"
