name: 🧪 Test Mock

on:
  workflow_dispatch:
    inputs:
      emergency:
        description: 'Emergency mode - Skip CI for specific users'
        required: false
        type: boolean
        default: false

jobs:
  check-user:
    name: Check user
    runs-on: ubuntu-latest
    outputs:
      is_allowed_user: ${{ steps.check_user.outputs.is_allowed_user }}
    steps:
      - name: Check if user is allowed
        id: check_user
        run: |
          # Lista de usuários permitidos para skip CI
          ALLOWED_USERS=("gaiel-sousa-rep")
          CURRENT_USER="${{ github.actor }}"

          # Verifica se o usuário atual está na lista
          if [[ " ${ALLOWED_USERS[@]} " =~ " ${CURRENT_USER} " ]]; then
            echo "is_allowed_user=true" >> $GITHUB_OUTPUT
          else
            echo "is_allowed_user=false" >> $GITHUB_OUTPUT
          fi

  test:
    name: 🧪 Test
    needs: check-user
    if: ${{ !(inputs.emergency && needs.check-user.outputs.is_allowed_user == 'true') || !inputs.emergency }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        run: |
          echo "Running tests..."
          echo "User: ${{ github.actor }}"
          echo "Emergency mode: ${{ inputs.emergency }}"
          echo "Is allowed user: ${{ needs.check-user.outputs.is_allowed_user }}"
          sleep 5 # Simula a execução dos testes

