name: Deploy and Send Status to Slack

on:
  workflow_dispatch:
    inputs:
      skip_restart:
        description: 'Set to true to skip the restart job'
        required: false
        default: 'false'
jobs:
  restart:
    if: ${{ 'true ' != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Restart
        run: echo "Restarting services..."

  sending-status-to-slack:
    if: needs.restart.result == 'success' || needs.restart.result == 'skipped'
    runs-on: ubuntu-latest
    needs:
      - restart
    steps:
      - name: Sending status to Slack
        run: echo "Sending deployment status to Slack..."

