name: Deploy and Send Status to Slack

on:
  workflow_dispatch: # Isso permite que o workflow seja executado manualmente, facilitando o teste com `act`

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Restart
        run: echo "Restarting services..."

  sending-status-to-slack:
    if: needs.restart.result == 'success' || needs.restart.result == 'skipped'
    runs-on: ubuntu-latest
    needs:
      - restart
    steps:
      - name: Sending status to Slack
        run: echo "Sending deployment status to Slack..."

