name: Restore Route53 Hosted Zone Backup

on:
  workflow_dispatch:
    inputs:
      BACKUP_FILE:
        description: "Backup file name in S3 bucket"
        required: true
      HOSTED_ZONE_ID:
        description: "Hosted Zone ID for restoration (leave empty to create a new one)"
        required: false
        default: ""
      HOSTED_ZONE_NAME:
        description: "Name for creating a new Hosted Zone, if it doesn't exist"
        required: false
        default: "example.com"

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # TODO: change to use assume role
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download backup file from S3
        run: |
          echo "Downloading backup file '${{ github.event.inputs.BACKUP_FILE }}' from bucket '${{ vars.ROUTE53_BACKUP_BUCKET }}'..."
          aws s3 cp s3://${{ vars.ROUTE53_BACKUP_BUCKET }}/${{ github.event.inputs.BACKUP_FILE }} .

      - name: Get password from Secrets Manager
        id: get_password
        run: |
          echo "Retrieving password from Secrets Manager..."
          # TODO: create AWS_SM_SECRET_ID in GitHub secrets
          PASSWORD=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SM_SECRET_ID }} --query 'SecretString' --output text)
          echo "password=$PASSWORD" >> $GITHUB_OUTPUT

      - name: Unzip backup file
        run: |
          echo "Unzipping file ${GITHUB_WORKSPACE}/${{ github.event.inputs.BACKUP_FILE }}..."
          unzip -P "${{ steps.get_password.outputs.password }}" ${{ github.event.inputs.BACKUP_FILE }}

      - name: Check or create Hosted Zone
        id: hosted_zone
        run: |
          if [ -z "${{ github.event.inputs.HOSTED_ZONE_ID }}" ]; then
            echo "No HOSTED_ZONE_ID provided, creating new Hosted Zone..."
            HOSTED_ZONE_ID=$(aws route53 create-hosted-zone --name ${{ github.event.inputs.HOSTED_ZONE_NAME }} --caller-reference $(date +%s) --query 'HostedZone.Id' --output text)
            echo "hosted_zone_id=$HOSTED_ZONE_ID" >> $GITHUB_OUTPUT
          else
            echo "Checking if Hosted Zone '${{ github.event.inputs.HOSTED_ZONE_ID }}' exists..."
            if aws route53 get-hosted-zone --id ${{ github.event.inputs.HOSTED_ZONE_ID }} > /dev/null 2>&1; then
              echo "Hosted Zone found."
              echo "hosted_zone_id=${{ github.event.inputs.HOSTED_ZONE_ID }}" >> $GITHUB_OUTPUT
            else
              echo "Hosted Zone not found, creating new one..."
              HOSTED_ZONE_ID=$(aws route53 create-hosted-zone --name ${{ github.event.inputs.HOSTED_ZONE_NAME }} --caller-reference $(date +%s) --query 'HostedZone.Id' --output text)
              echo "hosted_zone_id=$HOSTED_ZONE_ID" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Prepare change file (Change Batch)
        run: |
          echo "Preparing change file for import..."
          jq '{Changes: [.ResourceRecordSets[] | select(.Type != "NS" and .Type != "SOA") | {Action: "UPSERT", ResourceRecordSet: .} ]}' records.json > changes.json

      - name: Import records to Hosted Zone
        run: |
          HOSTED_ZONE_ID=${{ steps.hosted_zone.outputs.hosted_zone_id }}
          echo "Importing records to Hosted Zone $HOSTED_ZONE_ID..."
          aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch file://changes.json
