name: Backup Route53 Hosted Zone

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite (ajuste conforme necessário)
  workflow_dispatch:
    inputs:
      HOSTED_ZONE_ID:
        description: "ID da Hosted Zone do Route53"
        required: false
        default: "Z1234567890ABCDEFG"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Ajuste a região conforme necessário

      - name: Listar registros do Route53
        run: |
          echo "Recuperando registros da Hosted Zone ${{ github.event.inputs.HOSTED_ZONE_ID }}"
          aws route53 list-resource-record-sets --hosted-zone-id ${{ github.event.inputs.HOSTED_ZONE_ID }} > records.json

      - name: Obter senha do Secrets Manager
        id: get_password
        run: |
          echo "Recuperando senha do Secrets Manager..."
          PASSWORD=enois
          echo "password=$PASSWORD" >> $GITHUB_OUTPUT

      - name: Criar arquivo ZIP protegido por senha
        id: create_zip
        run: |
          HOSTED_ZONE_NAME="${{ github.event.inputs.HOSTED_ZONE_ID }}"
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          FILENAME="${TIMESTAMP}_${HOSTED_ZONE_NAME}.zip"
          echo "Criando arquivo $FILENAME com proteção por senha..."
          zip -P "${{ steps.get_password.outputs.password }}" "$FILENAME" records.json
          echo "zipfile=$FILENAME" >> $GITHUB_OUTPUT

      - name: Enviar arquivo para o bucket S3
        run: |
          echo "Enviando ${{ steps.create_zip.outputs.zipfile }} para o bucket S3..."
          aws s3 cp "${{ steps.create_zip.outputs.zipfile }}" s3://${{ vars.ROUTE53_BACKUP_BUCKET }}/
