name: Test Update Comment

on:
  workflow_dispatch:
  pull_request:

permissions:
  issues: write
  pull-requests: write

jobs:
  comment-test:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Deployment failed!

      - name: Create or Update PR Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚨 Deployment failed!  
            Check [GitHub Action logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          edit-mode: replace
